//
// AboutnewsData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class AboutnewsData: JSONEncodable {
    /** 新闻地址 */
    public var url: String?
    /** 新闻标题 */
    public var title: String?
    /** 新闻来源 */
    public var from: String?
    /** 赞数 */
    public var rank: Int32?
    /** 创建时间 */
    public var ptime: String?
    /** 来源地址 */
    public var pname: String?
    /** 图片地址 */
    public var img: String?
    /** 描述 */
    public var abs: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["url"] = self.url
        nillableDictionary["title"] = self.title
        nillableDictionary["from"] = self.from
        nillableDictionary["rank"] = self.rank?.encodeToJSON()
        nillableDictionary["ptime"] = self.ptime
        nillableDictionary["pname"] = self.pname
        nillableDictionary["img"] = self.img
        nillableDictionary["abs"] = self.abs
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
