//
// ChannelsData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ChannelsData: JSONEncodable {
    /** 频道的ID */
    public var id: Int32?
    /** 频道的名称 */
    public var cname: String?
    /** 频道状态 */
    public var state: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["cname"] = self.cname
        nillableDictionary["state"] = self.state?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
