//
// CommectCreate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class CommectCreate: JSONEncodable {
    /** 评论内容 */
    public var content: String?
    /** 点赞的数目 */
    public var commend: Int32?
    /** 创建评论时间 */
    public var ctime: String?
    /** 用户ID */
    public var uid: Int32?
    /** 用户名称 */
    public var uname: String?
    /** 用户头像 */
    public var avatar: String?
    /** 评论链接 */
    public var docid: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["content"] = self.content
        nillableDictionary["commend"] = self.commend?.encodeToJSON()
        nillableDictionary["ctime"] = self.ctime
        nillableDictionary["uid"] = self.uid?.encodeToJSON()
        nillableDictionary["uname"] = self.uname
        nillableDictionary["avatar"] = self.avatar
        nillableDictionary["docid"] = self.docid
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
