//
// CommentsData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class CommentsData: JSONEncodable {
    /** 评论ID */
    public var id: Int32?
    /** 评论正文 */
    public var content: String?
    /** 赞数 */
    public var commend: Int32?
    /** 创建时间 */
    public var ctime: String?
    /** 创建该评论的用户ID */
    public var uid: Int32?
    /** 创建该评论的用户名 */
    public var uname: String?
    /** 评论头像 */
    public var avatar: String?
    /** 该评论对应的新闻 docid */
    public var docid: String?
    /** 用户是否能对该条评论点赞，0、1 对应 可点、不可点 */
    public var upflag: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["content"] = self.content
        nillableDictionary["commend"] = self.commend?.encodeToJSON()
        nillableDictionary["ctime"] = self.ctime
        nillableDictionary["uid"] = self.uid?.encodeToJSON()
        nillableDictionary["uname"] = self.uname
        nillableDictionary["avatar"] = self.avatar
        nillableDictionary["docid"] = self.docid
        nillableDictionary["upflag"] = self.upflag?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
