//
// NewinfoData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class NewinfoData: JSONEncodable {
    /** 新闻的ID */
    public var nid: Int64?
    /** 新闻的原地址 */
    public var url: String?
    /** 用户评论信息地址 */
    public var docid: String?
    /** 新闻标题 */
    public var title: String?
    /** 新闻发生时间 */
    public var ptime: String?
    /** 来源名称 */
    public var pname: String?
    /** 新闻来源地址 */
    public var purl: String?
    /** 频道ID */
    public var channel: Int32?
    /** 收藏数 */
    public var collect: Int32?
    /** 关心数 */
    public var concern: Int32?
    /** 评论数目 */
    public var comment: Int32?
    /** 什么玩意的数目 */
    public var inum: Int32?
    /** 新闻的标签列表 */
    public var tags: [String]?
    /** 新闻的内容 */
    public var content: [NewinfoDataContent]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["nid"] = self.nid?.encodeToJSON()
        nillableDictionary["url"] = self.url
        nillableDictionary["docid"] = self.docid
        nillableDictionary["title"] = self.title
        nillableDictionary["ptime"] = self.ptime
        nillableDictionary["pname"] = self.pname
        nillableDictionary["purl"] = self.purl
        nillableDictionary["channel"] = self.channel?.encodeToJSON()
        nillableDictionary["collect"] = self.collect?.encodeToJSON()
        nillableDictionary["concern"] = self.concern?.encodeToJSON()
        nillableDictionary["comment"] = self.comment?.encodeToJSON()
        nillableDictionary["inum"] = self.inum?.encodeToJSON()
        nillableDictionary["tags"] = self.tags?.encodeToJSON()
        nillableDictionary["content"] = self.content?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
