//
// UserRegister.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class UserRegister: JSONEncodable {
    /** 游客ID ， 注册第三方用户的时候，必须本季已经存在一个游客的时候。 */
    public var muid: Int32?
    /** 三方用户相互合并时提供对应的三方用户ID */
    public var msuid: String?
    /** 用户类型注释1.本地注册用户 2游客用户 3微博用户 4微信用户 */
    public var utype: Int32?
    /** 用户平台注释 1.IOS 2安卓 3网页 4无法识别 */
    public var platform: Int32?
    /** 三方用户ID */
    public var suid: String?
    /** 三方用户Token */
    public var stoken: String?
    /** 三房token 过期时间 */
    public var sexpires: String?
    /** 用户名称 */
    public var uname: String?
    /** 用户性别 */
    public var gender: Int32?
    /** 用户头像 */
    public var avatar: String?
    /** 用户的不喜欢的标签列表 */
    public var averse: [String]?
    /** 用户的喜欢的标签列表 */
    public var prefer: [String]?
    /** 用户注册时所在的省份 */
    public var province: String?
    /** 用户注册时所在的城市 */
    public var city: String?
    /** 用户注册时所在的市区 */
    public var district: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["muid"] = self.muid?.encodeToJSON()
        nillableDictionary["msuid"] = self.msuid
        nillableDictionary["utype"] = self.utype?.encodeToJSON()
        nillableDictionary["platform"] = self.platform?.encodeToJSON()
        nillableDictionary["suid"] = self.suid
        nillableDictionary["stoken"] = self.stoken
        nillableDictionary["sexpires"] = self.sexpires
        nillableDictionary["uname"] = self.uname
        nillableDictionary["gender"] = self.gender?.encodeToJSON()
        nillableDictionary["avatar"] = self.avatar
        nillableDictionary["averse"] = self.averse?.encodeToJSON()
        nillableDictionary["prefer"] = self.prefer?.encodeToJSON()
        nillableDictionary["province"] = self.province
        nillableDictionary["city"] = self.city
        nillableDictionary["district"] = self.district
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
